import 'package:projectmercury/models/furniture.dart';
import 'package:projectmercury/models/slot.dart';
import 'package:projectmercury/pages/homePage/room.dart';

Room bedroom = Room(
  name: 'bedroom',
  width: 200,
  length: 215,
  unlockOrder: 1,
  floorTexture: "assets/textures/woodBoards.jpg",
  wallTexture: "assets/textures/greyWall.jpg",
  items: const [
    Furniture(
      name: 'doorway',
      direction: 'NE',
      width: 60,
      height: 60,
      xPosition: 25,
      yPosition: 180,
    ),
  ],
  slots: [
    Slot(
      room: 'bedroom',
      length: 35,
      width: 35,
      height: 35,
      yPosition: 70,
      xPosition: 70,
      items: const [
        Furniture(
          name: 'potted_plant',
          direction: 'NE',
          xPosition: 35,
          yPosition: 50,
          width: 35,
          height: 55,
        ),
        Furniture(
          name: 'square_lamp',
          direction: 'NE',
          xPosition: 35,
          yPosition: 50,
          width: 30,
          height: 60,
        ),
      ],
    ),
    Slot(
      room: 'bedroom',
      width: 45,
      height: 20,
      length: 50,
      yPosition: 150,
      xPosition: 50,
      overchargeRate: 0.5,
      items: const [
        Furniture(
          name: 'basic_bed',
          direction: 'NE',
          yPosition: 140,
          xPosition: 70,
          width: 70,
          height: 70,
        ),
        Furniture(
          name: 'plush_bed',
          direction: 'NE',
          yPosition: 140,
          xPosition: 70,
          width: 75,
          height: 75,
        ),
        /* Furniture( */
        /*   name: 'bed3', */
        /*   yPosition: 140, */
        /*   xPosition: 70, */
        /*   width: 70, */
        /*   height: 60, */
        /* ), */
      ],
    ),
  ],
);

Room livingroom = Room(
  width: 200,
  length: 250,
  unlockOrder: 2,
  floorTexture: 'assets/textures/woodBoards.jpg',
  wallTexture: 'assets/textures/floralWall.jpg',
  name: 'livingroom',
  items: const [
    Furniture(
      name: 'doorway',
      direction: 'NW',
      width: 60,
      height: 60,
      yPosition: 25,
      xPosition: 200,
    ),
    Furniture(
      name: 'doorway',
      direction: 'NE',
      width: 60,
      height: 60,
      yPosition: 200,
      xPosition: 25,
    ),
  ],
  slots: [
    Slot(
      room: 'livingroom',
      length: 60,
      width: 60,
      height: 25,
      yPosition: 120,
      xPosition: 170,
      doubleCharge: true,
      items: const [
        Furniture(
          name: 'basic_rug',
          direction: 'NE',
          xPosition: 130,
          yPosition: 110,
          width: 150,
          height: 150,
        ),
        Furniture(
          name: 'bear_rug',
          direction: 'NE',
          xPosition: 150,
          yPosition: 120,
          width: 100,
          height: 100,
        ),
        Furniture(
          name: 'coffee_table',
          direction: 'NE',
          xPosition: 175,
          yPosition: 140,
          width: 60,
          height: 50,
        ),
        Furniture(
          name: 'modern_coffee_table',
          direction: 'NE',
          xPosition: 175,
          yPosition: 140,
          width: 60,
          height: 50,
        ),
      ],
    ),
    Slot(
      room: 'livingroom',
      length: 35,
      width: 35,
      height: 35,
      yPosition: 70,
      xPosition: 270,
      items: const [
        Furniture(
          name: 'potted_plant',
          direction: 'NE',
          xPosition: 250,
          yPosition: 50,
          width: 35,
          height: 55,
        ),
        Furniture(
          name: 'square_lamp',
          direction: 'NE',
          xPosition: 250,
          yPosition: 50,
          width: 30,
          height: 60,
        ),
      ],
    ),
    Slot(
      room: 'livingroom',
      length: 35,
      width: 35,
      height: 35,
      yPosition: 70,
      xPosition: 70,
      items: const [
        Furniture(
          name: 'modern_lounge_chair',
          direction: 'NE',
          xPosition: 60,
          yPosition: 80,
          width: 50,
          height: 60,
        ),
        Furniture(
          name: 'plush_recliner',
          direction: 'NE',
          xPosition: 50,
          yPosition: 60,
          width: 45,
          height: 60,
        ),
        Furniture(
          name: 'leather_recliner',
          direction: 'NE',
          xPosition: 50,
          yPosition: 60,
          width: 45,
          height: 60,
        ),
      ],
    ),
    Slot(
      room: 'livingroom',
      length: 40,
      width: 30,
      height: 40,
      yPosition: 40,
      xPosition: 150,
      items: const [
        Furniture(
          name: 'live_laugh_love_painting',
          direction: 'NW',
          width: 45,
          height: 45,
          xPosition: 130,
          yPosition: 10,
        ),
        Furniture(
          name: 'vintage_tv',
          direction: 'NW',
          xPosition: 140,
          yPosition: 50,
          width: 50,
          height: 40,
        ),
        Furniture(
          name: 'modern_tv',
          direction: 'NW',
          yPosition: 20,
          xPosition: 120,
          width: 90,
          height: 80,
        ),
        Furniture(
          name: 'high_tech_tv_set',
          direction: 'NW',
          yPosition: 15,
          xPosition: 130,
          width: 100,
          height: 80,
        ),
      ],
    ),
    Slot(
      room: 'livingroom',
      length: 30,
      width: 40,
      height: 40,
      yPosition: 150,
      xPosition: 40,
      items: const [
        Furniture(
          name: 'fireplace',
          direction: 'NE',
          width: 90,
          height: 100,
          yPosition: 100,
          xPosition: 5,
        ),
        Furniture(
          name: 'bookcase',
          direction: 'NE',
          width: 60,
          height: 80,
          yPosition: 110,
          xPosition: 20,
        ),
        Furniture(
          name: 'rooster_painting',
          direction: 'NE',
          width: 45,
          height: 45,
          yPosition: 100,
          xPosition: 5,
        ),
      ],
    ),
    Slot(
      room: 'livingroom',
      length: 60,
      width: 30,
      height: 40,
      yPosition: 200,
      xPosition: 140,
      items: const [
        Furniture(
          name: 'basic_sofa',
          direction: 'SE',
          yPosition: 200,
          xPosition: 165,
          width: 100,
          height: 60,
        ),
        Furniture(
          name: 'modern_sofa',
          direction: 'SE',
          yPosition: 200,
          xPosition: 165,
          width: 100,
          height: 60,
        ),
        Furniture(
          name: 'plush_sofa',
          direction: 'SE',
          yPosition: 200,
          xPosition: 165,
          width: 100,
          height: 60,
        ),
        Furniture(
          name: 'leather_sofa',
          direction: 'SE',
          yPosition: 200,
          xPosition: 165,
          width: 100,
          height: 60,
        ),
      ],
    ),
  ],
);

Room bathroom = Room(
  name: 'bathroom',
  width: 200,
  length: 150,
  unlockOrder: 3,
  floorTexture: "assets/textures/bathroomTiles.jpg",
  wallTexture: "assets/textures/greyWall.jpg",
  items: const [],
  slots: [
    Slot(
      room: 'bathroom',
      width: 30,
      length: 30,
      height: 30,
      yPosition: 70,
      xPosition: 70,
      items: const [
        Furniture(
          name: 'shower',
          direction: 'NW',
          width: 60,
          height: 60,
          yPosition: 40,
          xPosition: 40,
        ),
      ],
    ),
    Slot(
      room: 'bathroom',
      width: 30,
      length: 30,
      height: 30,
      yPosition: 150,
      xPosition: 70,
      items: const [
        Furniture(
          name: 'toilet',
          direction: 'NE',
          width: 30,
          height: 35,
          yPosition: 150,
          xPosition: 60,
        ),
      ],
    ),
    Slot(
      room: 'bathroom',
      width: 30,
      length: 60,
      height: 30,
      yPosition: 70,
      xPosition: 120,
      items: const [
        Furniture(
          name: 'bathtub',
          direction: 'SW',
          width: 60,
          height: 50,
          yPosition: 60,
          xPosition: 160,
        ),
      ],
    ),
  ],
);

Room kitchen = Room(
  name: 'kitchen',
  width: 200,
  length: 215,
  unlockOrder: 4,
  floorTexture: "assets/textures/woodBoards.jpg",
  wallTexture: "assets/textures/floralWall.jpg",
  items: const [
    Furniture(
      name: 'doorway',
      direction: 'NE',
      width: 60,
      height: 60,
      yPosition: 180,
      xPosition: 20,
    ),
  ],
  slots: [
    Slot(
      room: 'kitchen',
      length: 30,
      width: 35,
      height: 40,
      yPosition: 50,
      xPosition: 45,
      items: const [
        Furniture(
          name: 'mini_fridge',
          direction: 'NE',
          width: 40,
          height: 40,
          yPosition: 60,
          xPosition: 55,
        ),
        Furniture(
          name: 'fridge',
          direction: 'NE',
          width: 60,
          height: 60,
          yPosition: 50,
          xPosition: 30,
        ),
        Furniture(
          name: 'large_fridge',
          direction: 'NE',
          width: 70,
          height: 75,
          yPosition: 50,
          xPosition: 25,
        ),
      ],
    ),
  ],
);

Room diningroom = Room(
  name: 'diningroom',
  width: 200,
  length: 225,
  unlockOrder: 5,
  floorTexture: "assets/textures/woodBoards.jpg",
  wallTexture: "assets/textures/greyWall.jpg",
  items: const [
    Furniture(
      name: 'doorway',
      direction: 'NE',
      width: 60,
      height: 60,
      yPosition: 170,
      xPosition: 20,
    ),
  ],
  slots: [
    Slot(
      room: 'diningroom',
      length: 60,
      width: 60,
      height: 25,
      yPosition: 130,
      xPosition: 150,
      items: const [
        Furniture(
          name: 'basic_dining_table',
          direction: 'NE',
          xPosition: 140,
          yPosition: 120,
          width: 100,
          height: 75,
        ),
      ],
    ),
    Slot(
      room: 'diningroom',
      length: 40,
      width: 30,
      height: 40,
      yPosition: 40,
      xPosition: 180,
      items: const [
        Furniture(
          name: 'window',
          direction: 'NW',
          xPosition: 160,
          yPosition: 10,
          width: 40,
          height: 50,
        ),
      ],
    ),
  ],
);

Room washroom = const Room(
  name: 'washroom',
  width: 200,
  length: 175,
  unlockOrder: 6,
  floorTexture: "assets/textures/bathroomTiles.jpg",
  wallTexture: "assets/textures/greyWall.jpg",
  items: [
    Furniture(
      name: 'dryer',
      direction: 'NE',
      width: 40,
      height: 40,
      yPosition: 80,
      xPosition: 60,
    ),
    Furniture(
      name: 'washer',
      direction: 'NE',
      width: 40,
      height: 40,
      yPosition: 110,
      xPosition: 60,
    ),
  ],
  slots: [],
);
