import 'package:projectmercury/models/store_item.dart';

const List<StoreItem> storeItems = [
  StoreItem(
    name: 'Bear Rug',
    price: 300,
    item: 'bear_rug',
    seller: Seller.furnitureClassics,
  ),
  StoreItem(
    name: 'Discount Rug',
    price: 150,
    item: 'basic_rug',
    seller: Seller.secondhandFurniture,
  ),
  StoreItem(
    name: 'Coffee Table',
    price: 200,
    item: 'coffee_table',
    seller: Seller.phillipesFurniture,
  ),
  StoreItem(
    name: 'Modern Coffee Table',
    price: 200,
    item: 'modern_coffee_table',
    seller: Seller.furnitureNow,
  ),
  StoreItem(
    name: 'Leather Sofa',
    price: 300,
    item: 'leather_sofa',
    seller: Seller.fineFurnitureImports,
  ),
  StoreItem(
    name: 'Discount Sofa',
    price: 150,
    item: 'basic_sofa',
    seller: Seller.furnitureDunRyte,
  ),
  StoreItem(
    name: 'Plush Sofa',
    price: 250,
    item: 'plush_sofa',
    seller: Seller.maggiesFurnitureDepot,
  ),
  StoreItem(
    name: 'Modern Sofa',
    price: 200,
    item: 'modern_sofa',
    seller: Seller.theFurnitureSpot,
  ),
  StoreItem(
    name: 'Vintage TV',
    price: 250,
    item: 'vintage_tv',
    seller: Seller.marcelasAntiques,
  ),
  StoreItem(
    name: 'Flatscreen TV',
    price: 400,
    item: 'modern_tv',
    seller: Seller.modernElectronicsAndMore,
  ),
  StoreItem(
    name: 'Luxery TV Set',
    price: 600,
    item: 'high_tech_tv_set',
    seller: Seller.modernElectronicsAndMore,
  ),
  StoreItem(
    name: 'The Rooster',
    price: 150,
    item: 'rooster_painting',
    seller: Seller.marcelasAntiques,
  ),
  StoreItem(
    name: 'Rob Boss Painting',
    price: 150,
    item: 'landscape_painting',
    seller: Seller.marcelasAntiques,
  ),
  StoreItem(
    name: 'Live, Laugh, Love',
    price: 100,
    item: 'live_laugh_love_painting',
    seller: Seller.furnitureDunRyte,
  ),
  StoreItem(
    name: 'Potted Plant',
    price: 100,
    item: 'potted_plant',
    seller: Seller.homePatioAndLawn,
  ),
  StoreItem(
    name: 'Floor Lamp',
    price: 150,
    item: 'square_lamp',
    seller: Seller.maggiesFurnitureDepot,
  ),
  StoreItem(
    name: 'Fireplace',
    price: 400,
    item: 'fireplace',
    seller: Seller.topNotchContractors,
  ),
  StoreItem(
    name: 'Bookcase',
    price: 200,
    item: 'bookcase',
    seller: Seller.marcelasAntiques,
  ),
  StoreItem(
    name: 'Desk',
    price: 300,
    item: 'desk',
    seller: Seller.marcelasAntiques,
  ),
  StoreItem(
    name: 'Plush Recliner',
    price: 250,
    item: 'plush_recliner',
    seller: Seller.furnitureYourWay,
  ),
  StoreItem(
    name: 'Leather Recliner',
    price: 300,
    item: 'leather_recliner',
    seller: Seller.furnitureYourWay,
  ),
  StoreItem(
    name: 'Modern Lounge Chair',
    price: 200,
    item: 'modern_lounge_chair',
    seller: Seller.meublesdeMoreau,
  ),
  StoreItem(
    name: 'Discount Bed',
    price: 400,
    item: 'basic_bed',
    seller: Seller.maggiesFurnitureDepot,
  ),
  StoreItem(
    name: 'Plush Bed',
    price: 500,
    item: 'plush_bed',
    seller: Seller.maggiesFurnitureDepot,
  ),
  StoreItem(
    name: 'Shower',
    price: 400,
    item: 'shower',
  ),
  StoreItem(
    name: 'Toilet',
    price: 200,
    item: 'toilet',
  ),
  StoreItem(
    name: 'Bathtub',
    price: 200,
    item: 'bathtub',
  ),
  StoreItem(
    name: 'Mini Fridge',
    price: 200,
    item: 'mini_fridge',
  ),
  StoreItem(
    name: 'Discount Fridge',
    price: 400,
    item: 'fridge',
  ),
  StoreItem(
    name: 'Luxery Fridge',
    price: 600,
    item: 'large_fridge',
  ),
  StoreItem(
    name: 'Dining Table',
    price: 550,
    item: 'basic_dining_table',
  ),
  StoreItem(
    name: 'Window',
    price: 350,
    item: 'window',
  ),
  StoreItem(
    name: 'Stove',
    price: 450,
    item: 'stove',
  ),
  StoreItem(
    name: 'Electric Stove',
    price: 550,
    item: 'electric_stove',
  ),
  StoreItem(
    name: 'Red Rug',
    price: 60,
    item: 'bathroom_rug_red',
  ),
  StoreItem(
    name: 'Brown Rug',
    price: 70,
    item: 'bathroom_rug_brown',
  ),
  StoreItem(
    name: 'White Rug',
    price: 80,
    item: 'bathroom_rug_white',
  ),
  StoreItem(
    name: 'Computer',
    price: 600,
    item: 'computer',
  ),
  StoreItem(
    name: 'Office Chair',
    price: 80,
    item: 'desk_chair',
  ),
];
